// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Restaritem is the predicate function for restaritem builders.
type Restaritem func(*sql.Selector)
