
services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=oprox
      - POSTGRES_PASSWORD=oprox
      - POSTGRES_DB=oprox
    ports:
      - "5432:5432"
    volumes:
      - './db/pg:/docker-entrypoint-initdb.d'