
services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=oprox
      - POSTGRES_PASSWORD=oprox
      - POSTGRES_DB=oprox
    ports:
      - "5555:5432"
    volumes:
      - pg:/var/lib/postgresql/data

  imaginary:
    image: ghcr.io/wordpress/openverse-imaginary:latest
    restart: always
    ports:
      - "5556:9000"

  meilisearch:
    image: getmeili/meilisearch:latest
    ports:
      - 7700:7700
    volumes:
      - meili_data:/meili_data

volumes:
  pg:
  meili_data: