
services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=oprox
      - POSTGRES_PASSWORD=oprox
      - POSTGRES_DB=oprox
    ports:
      - "5555:5432"
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: