version: "2"

tasks:
  default:
    cmds:
      - go build -v ./cmd/apiserver
      - apiserver
    env:
      GREET: lellol

  test:
    cmds:
      - go test -v -race -timeout 30s ./...
  healthcheck:
    cmds:
      - http HEAD httpbin.org/get
