baseURL: "https://re-star.ru/"
languageCode: "ru"
title: "Re-Star"
module:
  mounts:
    - source: content
      target: content
    - source: prebuild/public/item
      target: content/item
