// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package repo

import ()

type Restaritem struct {
	ID       int64
	Onceguid string
	Name     string
	Sku      string
	Itemguid string
}
