// Code generated by entc, DO NOT EDIT.

package ent

import (
	"backend/ent/restaritem"
	"backend/pkg/photo"
	"backend/pkg/work"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RestaritemCreate is the builder for creating a Restaritem entity.
type RestaritemCreate struct {
	config
	mutation *RestaritemMutation
	hooks    []Hook
}

// SetOnecGUID sets the "onecGUID" field.
func (rc *RestaritemCreate) SetOnecGUID(s string) *RestaritemCreate {
	rc.mutation.SetOnecGUID(s)
	return rc
}

// SetName sets the "name" field.
func (rc *RestaritemCreate) SetName(s string) *RestaritemCreate {
	rc.mutation.SetName(s)
	return rc
}

// SetNillableName sets the "name" field if the given value is not nil.
func (rc *RestaritemCreate) SetNillableName(s *string) *RestaritemCreate {
	if s != nil {
		rc.SetName(*s)
	}
	return rc
}

// SetSku sets the "sku" field.
func (rc *RestaritemCreate) SetSku(s string) *RestaritemCreate {
	rc.mutation.SetSku(s)
	return rc
}

// SetNillableSku sets the "sku" field if the given value is not nil.
func (rc *RestaritemCreate) SetNillableSku(s *string) *RestaritemCreate {
	if s != nil {
		rc.SetSku(*s)
	}
	return rc
}

// SetItemGUID sets the "itemGUID" field.
func (rc *RestaritemCreate) SetItemGUID(s string) *RestaritemCreate {
	rc.mutation.SetItemGUID(s)
	return rc
}

// SetNillableItemGUID sets the "itemGUID" field if the given value is not nil.
func (rc *RestaritemCreate) SetNillableItemGUID(s *string) *RestaritemCreate {
	if s != nil {
		rc.SetItemGUID(*s)
	}
	return rc
}

// SetCharGUID sets the "charGUID" field.
func (rc *RestaritemCreate) SetCharGUID(s string) *RestaritemCreate {
	rc.mutation.SetCharGUID(s)
	return rc
}

// SetNillableCharGUID sets the "charGUID" field if the given value is not nil.
func (rc *RestaritemCreate) SetNillableCharGUID(s *string) *RestaritemCreate {
	if s != nil {
		rc.SetCharGUID(*s)
	}
	return rc
}

// SetDescription sets the "description" field.
func (rc *RestaritemCreate) SetDescription(s string) *RestaritemCreate {
	rc.mutation.SetDescription(s)
	return rc
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (rc *RestaritemCreate) SetNillableDescription(s *string) *RestaritemCreate {
	if s != nil {
		rc.SetDescription(*s)
	}
	return rc
}

// SetInspector sets the "inspector" field.
func (rc *RestaritemCreate) SetInspector(s string) *RestaritemCreate {
	rc.mutation.SetInspector(s)
	return rc
}

// SetNillableInspector sets the "inspector" field if the given value is not nil.
func (rc *RestaritemCreate) SetNillableInspector(s *string) *RestaritemCreate {
	if s != nil {
		rc.SetInspector(*s)
	}
	return rc
}

// SetInspection sets the "inspection" field.
func (rc *RestaritemCreate) SetInspection(s []string) *RestaritemCreate {
	rc.mutation.SetInspection(s)
	return rc
}

// SetPhotos sets the "photos" field.
func (rc *RestaritemCreate) SetPhotos(ph []photo.Photo) *RestaritemCreate {
	rc.mutation.SetPhotos(ph)
	return rc
}

// SetWorks sets the "works" field.
func (rc *RestaritemCreate) SetWorks(w []work.Work) *RestaritemCreate {
	rc.mutation.SetWorks(w)
	return rc
}

// Mutation returns the RestaritemMutation object of the builder.
func (rc *RestaritemCreate) Mutation() *RestaritemMutation {
	return rc.mutation
}

// Save creates the Restaritem in the database.
func (rc *RestaritemCreate) Save(ctx context.Context) (*Restaritem, error) {
	var (
		err  error
		node *Restaritem
	)
	if len(rc.hooks) == 0 {
		if err = rc.check(); err != nil {
			return nil, err
		}
		node, err = rc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*RestaritemMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = rc.check(); err != nil {
				return nil, err
			}
			rc.mutation = mutation
			if node, err = rc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(rc.hooks) - 1; i >= 0; i-- {
			if rc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = rc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, rc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (rc *RestaritemCreate) SaveX(ctx context.Context) *Restaritem {
	v, err := rc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rc *RestaritemCreate) Exec(ctx context.Context) error {
	_, err := rc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rc *RestaritemCreate) ExecX(ctx context.Context) {
	if err := rc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rc *RestaritemCreate) check() error {
	if _, ok := rc.mutation.OnecGUID(); !ok {
		return &ValidationError{Name: "onecGUID", err: errors.New(`ent: missing required field "Restaritem.onecGUID"`)}
	}
	return nil
}

func (rc *RestaritemCreate) sqlSave(ctx context.Context) (*Restaritem, error) {
	_node, _spec := rc.createSpec()
	if err := sqlgraph.CreateNode(ctx, rc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (rc *RestaritemCreate) createSpec() (*Restaritem, *sqlgraph.CreateSpec) {
	var (
		_node = &Restaritem{config: rc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: restaritem.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: restaritem.FieldID,
			},
		}
	)
	if value, ok := rc.mutation.OnecGUID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: restaritem.FieldOnecGUID,
		})
		_node.OnecGUID = value
	}
	if value, ok := rc.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: restaritem.FieldName,
		})
		_node.Name = value
	}
	if value, ok := rc.mutation.Sku(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: restaritem.FieldSku,
		})
		_node.Sku = value
	}
	if value, ok := rc.mutation.ItemGUID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: restaritem.FieldItemGUID,
		})
		_node.ItemGUID = value
	}
	if value, ok := rc.mutation.CharGUID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: restaritem.FieldCharGUID,
		})
		_node.CharGUID = value
	}
	if value, ok := rc.mutation.Description(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: restaritem.FieldDescription,
		})
		_node.Description = value
	}
	if value, ok := rc.mutation.Inspector(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: restaritem.FieldInspector,
		})
		_node.Inspector = value
	}
	if value, ok := rc.mutation.Inspection(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  value,
			Column: restaritem.FieldInspection,
		})
		_node.Inspection = value
	}
	if value, ok := rc.mutation.Photos(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  value,
			Column: restaritem.FieldPhotos,
		})
		_node.Photos = value
	}
	if value, ok := rc.mutation.Works(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  value,
			Column: restaritem.FieldWorks,
		})
		_node.Works = value
	}
	return _node, _spec
}

// RestaritemCreateBulk is the builder for creating many Restaritem entities in bulk.
type RestaritemCreateBulk struct {
	config
	builders []*RestaritemCreate
}

// Save creates the Restaritem entities in the database.
func (rcb *RestaritemCreateBulk) Save(ctx context.Context) ([]*Restaritem, error) {
	specs := make([]*sqlgraph.CreateSpec, len(rcb.builders))
	nodes := make([]*Restaritem, len(rcb.builders))
	mutators := make([]Mutator, len(rcb.builders))
	for i := range rcb.builders {
		func(i int, root context.Context) {
			builder := rcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RestaritemMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, rcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, rcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, rcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (rcb *RestaritemCreateBulk) SaveX(ctx context.Context) []*Restaritem {
	v, err := rcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rcb *RestaritemCreateBulk) Exec(ctx context.Context) error {
	_, err := rcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rcb *RestaritemCreateBulk) ExecX(ctx context.Context) {
	if err := rcb.Exec(ctx); err != nil {
		panic(err)
	}
}
