// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// RestaritemsColumns holds the columns for the "restaritems" table.
	RestaritemsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "onec_guid", Type: field.TypeString},
		{Name: "name", Type: field.TypeString, Nullable: true},
		{Name: "sku", Type: field.TypeString, Nullable: true},
		{Name: "item_guid", Type: field.TypeString, Nullable: true},
		{Name: "char_guid", Type: field.TypeString, Nullable: true},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "inspector", Type: field.TypeString, Nullable: true},
		{Name: "inspection", Type: field.TypeJSON, Nullable: true},
	}
	// RestaritemsTable holds the schema information for the "restaritems" table.
	RestaritemsTable = &schema.Table{
		Name:       "restaritems",
		Columns:    RestaritemsColumns,
		PrimaryKey: []*schema.Column{RestaritemsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		RestaritemsTable,
	}
)

func init() {
}
