// Code generated by entc, DO NOT EDIT.

package restaritem

const (
	// Label holds the string label denoting the restaritem type in the database.
	Label = "restaritem"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldOnecGUID holds the string denoting the onecguid field in the database.
	FieldOnecGUID = "onec_guid"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldSku holds the string denoting the sku field in the database.
	FieldSku = "sku"
	// FieldItemGUID holds the string denoting the itemguid field in the database.
	FieldItemGUID = "item_guid"
	// FieldCharGUID holds the string denoting the charguid field in the database.
	FieldCharGUID = "char_guid"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldInspector holds the string denoting the inspector field in the database.
	FieldInspector = "inspector"
	// FieldInspection holds the string denoting the inspection field in the database.
	FieldInspection = "inspection"
	// Table holds the table name of the restaritem in the database.
	Table = "restaritems"
)

// Columns holds all SQL columns for restaritem fields.
var Columns = []string{
	FieldID,
	FieldOnecGUID,
	FieldName,
	FieldSku,
	FieldItemGUID,
	FieldCharGUID,
	FieldDescription,
	FieldInspector,
	FieldInspection,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
