### список продуктов
GET {{host}}/1c/products/

### поиск продуктов
GET {{host}}/search/cs125

### поиск так же только через параметр
GET {{host}}/catalog?q=cs125

### обновление прайс листа
POST {{host}}/1c/updatePricelist?limit=20

### получить список продуктов
GET {{host}}/onec/products

### получить товары в ячейке ошибка
GET {{host}}/warehouse/cell/cs

### получить товары в ячейке ок
GET {{host}}/warehouse/cell/N2_15-G-06

### сгенерировать qr код
POST {{host}}/qr

### сгенерировать qr код
POST {{host}}/qr
Content-Type: application/json

{
  "width": 58,
  "height": 30,
  "code": "https://re-star.ru/oprox/warehouse/cell/N2_15-G-06",
  "text": ["артикул", "характеристика", "наименование"]
}

