name: Go
on:
  push:
    paths:
      - '.github/workflows/frontend.yml'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
#       - name: Set up Go 1.17
#         uses: actions/setup-go@v2
#         with:
#           go-version: 1.17
#         id: go

#       - name: Build
#         run: go build -v ./cmd/apiserver
#         working-directory: backend
