name: Static site deploy
on:
  push:
    paths:
      - 'site/**'
      - '.github/workflows/site.yaml'

# env:
#   REPO: ${{github.repository}}
#   USERNAME: ${{github.actor}}
#   GITHUB_REF: ${{github.ref}}
#   GITHUB_SHA: ${{github.sha}}
#   GITHUB_PACKAGE_TOKEN: ${{secrets.GITHUB_TOKEN}}
#   K: '02'

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./site
    steps:
      - uses: actions/checkout@v3
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
      - name: Build
        run: hugo --gc --minify

      - name: copy dist via rsync
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_RESTAR }}
          REMOTE_HOST: re-star.ru
          REMOTE_USER: root

          ARGS: >-
            -rtgoDzvO
            --delete
            --chown=caddy:caddy
          SOURCE: 'site/public/'
          TARGET: '/var/lib/caddy/deploy'
