### список продуктов
GET {{host}}/1c/products/

### обновление прайс листа
POST {{host}}/1c/updatePricelist?limit=20

### получить список продуктов
GET {{host}}/onec/products

### сгенерировать qr код
POST {{host}}/qr

### сгенерировать qr код
POST {{host}}/qr
Content-Type: application/json

{
  "width": 58,
  "height": 30,
  "code": "https://re-star.ru/warehouse/cell/N2_15-G-06",
  "text": ["артикул", "характеристика", "наименование"]
}

### get once info by cell
GET http://10.51.0.10:19201/sm1/hs/tsd/cell/N2_15-G-06/records
Authorization: Basic QVBJOjZPN0VIRFdTMFNrJHlaJWk4MHA1
