PUT replica.restar:8100/s3/image
Content-Type: image/jpeg
< '/home/restar/Desktop/Новая%20папка/1.png'

###
GET http://localhost:8100/1c/products

###
POST  http://localhost:8100/1c/updatePricelist?limit=20

### get users
GET http://localhost:8100/onec/products