### список продуктов
GET {{host}}/1c/products/

### обновление прайс листа
POST {{host}}/1c/updatePricelist?limit=20

### получить список продуктов
GET {{host}}/onec/products

### сгенерировать qr код
POST {{host}}/qr